# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://karpatic.github.io/test123/"

git_url = "https://github.com/karpatic/test123/tree/master/"

def custom_doc_links(name): return None
